[package]
name = "neumann-user"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
linked_list_allocator = "0.10"
spin = "0.9"

[lib]
name = "neumann_rt"
path = "src/lib.rs"
test = false
bench = false

[[bin]]
name = "sh"
test = false
bench = false

[[bin]]
name = "echo"
test = false
bench = false

[[bin]]
name = "cat"
test = false
bench = false

[[bin]]
name = "ptrtest"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
debug = false
strip = true
codegen-units = 1

[[bin]]
name = "ls"
test = false
bench = false

[[bin]]
name = "mkdir"
test = false
bench = false

[[bin]]
name = "threads"
test = false
bench = false

[[bin]]
name = "heaptest"
test = false
bench = false
